sudo: required

language: node

services:
  - docker

branches:
  only:
  - master
  - develop
  
jobs:
  include:
    - stage: Hello-node-travis
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      - docker build -t $DOCKER_USERNAME/hellonode:travis .;
      - docker push $DOCKER_USERNAME/hellonode:travis;
